name: CI

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "master" ]

concurrency:
  group: cmake-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/runner-images
        os: [macos-13, macos-14, ubuntu-24.04]

    runs-on: ${{matrix.os}}

    steps:

    - name: Install dependencies (macOS)
      if: startsWith(matrix.os, 'macos-')
      run: |
        brew install virtualenv

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build test
      run: ./build.sh
      working-directory: ${{github.workspace}}/test

    - name: Run test
      run: ./test.sh
      working-directory: ${{github.workspace}}/test

  benchmark:
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/runner-images
        os: [macos-13, macos-14]

    runs-on: ${{matrix.os}}

    steps:

    - name: Install dependencies (macOS)
      if: startsWith(matrix.os, 'macos-')
      run: |
        brew install flatbuffers

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Build benchmark
      run: ./build.sh
      working-directory: ${{github.workspace}}/bench

    - name: Run benchmark
      run: ./run.sh
      working-directory: ${{github.workspace}}/bench
